[all] Rename pyobas to pyoaev
Co-authored-by: Guillaume Paris <guillaume.paris@filigran.io>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -75,47 +75,101 @@ jobs:
       - run: sudo apt-get update -qq && sudo apt install curl gettext-base
       - run:
           working_directory: ~/openaev/http-query
-          name: Build Docker image openaev/injector-http-query
+          name: Build Docker image openbas/injector-http-query
           command: |
-            TAGS="-t openaev/injector-http-query:${CIRCLE_TAG} -t openbas/injector-http-query:${CIRCLE_TAG}"
-            $IS_LATEST && TAGS="$TAGS -t openaev/injector-http-query:latest -t openbas/injector-http-query:latest"
+            TAGS="-t openbas/injector-http-query:${CIRCLE_TAG}"
+            $IS_LATEST && TAGS="$TAGS -t openbas/injector-http-query:latest"
             docker build --progress=plain $TAGS .
       - run:
           working_directory: ~/openaev/nmap
-          name: Build Docker image openaev/injector-nmap
+          name: Build Docker image openbas/injector-nmap
           command: |
-            TAGS="-t openaev/injector-nmap:${CIRCLE_TAG} -t openbas/injector-nmap:${CIRCLE_TAG}"
-            $IS_LATEST && TAGS="$TAGS -t openaev/injector-nmap:latest -t openbas/injector-nmap:latest"
+            TAGS="-t openbas/injector-nmap:${CIRCLE_TAG}"
+            $IS_LATEST && TAGS="$TAGS -t openbas/injector-nmap:latest"
             docker build --progress=plain $TAGS .
       - run:
           working_directory: ~/openaev/nuclei
-          name: Build Docker image openaev/injector-nuclei
+          name: Build Docker image openbas/injector-nuclei
           command: |
-            TAGS="-t openaev/injector-nuclei:${CIRCLE_TAG} -t openbas/injector-nuclei:${CIRCLE_TAG}"
-            $IS_LATEST && TAGS="$TAGS -t openaev/injector-nuclei:latest -t openbas/injector-nuclei:latest"
+            TAGS="-t openbas/injector-nuclei:${CIRCLE_TAG}"
+            $IS_LATEST && TAGS="$TAGS -t openbas/injector-nuclei:latest"
             docker build --progress=plain $TAGS .
       - run:
           working_directory: ~/openaev/aws
-          name: Build Docker image openaev/injector-aws
+          name: Build Docker image openbas/injector-aws
           command: |
-            TAGS="-t openaev/injector-aws:${CIRCLE_TAG} -t openbas/injector-aws:${CIRCLE_TAG}"
-            $IS_LATEST && TAGS="$TAGS -t openaev/injector-aws:latest -t openbas/injector-aws:latest"
+            TAGS="-t openbas/injector-aws:${CIRCLE_TAG}"
+            $IS_LATEST && TAGS="$TAGS -t openbas/injector-aws:latest"
             docker build --progress=plain $TAGS .
       - run:
           name: Publish Docker Image to Docker Hub
           command: |
             echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
-            $IS_LATEST && docker push openaev/injector-http-query:latest && docker push openbas/injector-http-query:latest
-            docker push openaev/injector-http-query:${CIRCLE_TAG} && docker push openbas/injector-http-query:${CIRCLE_TAG}
-            $IS_LATEST && docker push openaev/injector-nmap:latest && docker push openbas/injector-nmap:latest
-            docker push openaev/injector-nmap:${CIRCLE_TAG} && docker push openbas/injector-nmap:${CIRCLE_TAG}
-            $IS_LATEST && docker push openaev/injector-nuclei:latest && docker push openbas/injector-nuclei:latest
-            docker push openaev/injector-nuclei:${CIRCLE_TAG} && docker push openbas/injector-nuclei:${CIRCLE_TAG}
-            $IS_LATEST && docker push openaev/injector-aws:latest && docker push openbas/injector-aws:latest
-            docker push openaev/injector-aws:${CIRCLE_TAG} && docker push openbas/injector-aws:${CIRCLE_TAG}
+            $IS_LATEST && docker push openbas/injector-http-query:latest
+            docker push docker push openbas/injector-http-query:${CIRCLE_TAG}
+            $IS_LATEST && docker push openbas/injector-nmap:latest
+            docker push docker push openbas/injector-nmap:${CIRCLE_TAG}
+            $IS_LATEST && docker push openbas/injector-nuclei:latest
+            docker push docker push openbas/injector-nuclei:${CIRCLE_TAG}
+            $IS_LATEST && docker push openbas/injector-aws:latest
+            docker push docker push openbas/injector-aws:${CIRCLE_TAG}
       - slack/notify:
           event: fail
           template: basic_fail_1
+  # build_1:
+  #   working_directory: ~/openaev
+  #   docker:
+  #     - image: cimg/base:stable-20.04
+  #   environment:
+  #     LATEST_SEMANTIC_VERSION: $(git tag --sort=-v:refname | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
+  #     IS_LATEST: $([ "$CIRCLE_TAG" = "$LATEST_SEMANTIC_VERSION" ] && echo "true" || echo "false")
+  #   steps:
+  #     - checkout
+  #     - setup_remote_docker
+  #     - run: sudo apt-get update -qq && sudo apt install curl gettext-base
+  #     - run:
+  #         working_directory: ~/openaev/http-query
+  #         name: Build Docker image openaev/injector-http-query
+  #         command: |
+  #           TAGS="-t openaev/injector-http-query:${CIRCLE_TAG}"
+  #           $IS_LATEST && TAGS="$TAGS -t openaev/injector-http-query:latest"
+  #           docker build --progress=plain $TAGS .
+  #     - run:
+  #         working_directory: ~/openaev/nmap
+  #         name: Build Docker image openaev/injector-nmap
+  #         command: |
+  #           TAGS="-t openaev/injector-nmap:${CIRCLE_TAG}"
+  #           $IS_LATEST && TAGS="$TAGS -t openaev/injector-nmap:latest"
+  #           docker build --progress=plain $TAGS .
+  #     - run:
+  #         working_directory: ~/openaev/nuclei
+  #         name: Build Docker image openaev/injector-nuclei
+  #         command: |
+  #           TAGS="-t openaev/injector-nuclei:${CIRCLE_TAG}"
+  #           $IS_LATEST && TAGS="$TAGS -t openaev/injector-nuclei:latest"
+  #           docker build --progress=plain $TAGS .
+  #     - run:
+  #         working_directory: ~/openaev/aws
+  #         name: Build Docker image openaev/injector-aws
+  #         command: |
+  #           TAGS="-t openaev/injector-aws:${CIRCLE_TAG}"
+  #           $IS_LATEST && TAGS="$TAGS -t openaev/injector-aws:latest"
+  #           docker build --progress=plain $TAGS .
+  #     - run:
+  #         name: Publish Docker Image to Docker Hub
+  #         command: |
+  #           echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
+  #           $IS_LATEST && docker push openaev/injector-http-query:latest
+  #           docker push openaev/injector-http-query:${CIRCLE_TAG}
+  #           $IS_LATEST && docker push openaev/injector-nmap:latest
+  #           docker push openaev/injector-nmap:${CIRCLE_TAG}
+  #           $IS_LATEST && docker push openaev/injector-nuclei:latest
+  #           docker push openaev/injector-nuclei:${CIRCLE_TAG}
+  #           $IS_LATEST && docker push openaev/injector-aws:latest
+  #           docker push openaev/injector-aws:${CIRCLE_TAG}
+  #     - slack/notify:
+  #         event: fail
+  #         template: basic_fail_1
   build_rolling_1:
     working_directory: ~/openaev
     docker:
@@ -125,9 +179,9 @@ jobs:
       - setup_remote_docker
       - run: sudo apt-get update -qq && sudo apt install curl gettext-base
       - run:
-         working_directory: ~/openaev
-         name: Replace pyoaev requirement of stable version with latest main branch code
-         command: find . -name requirements.txt -exec sed 's|^pyoaev==.*$|pyoaev @ git+https://github.com/OpenAEV-Platform/client-python@main|' -i {} \;
+          working_directory: ~/openaev
+          name: Replace pyoaev requirement of stable version with latest main branch code
+          command: find . -name requirements.txt -exec sed 's|^pyoaev==.*$|pyoaev @ git+https://github.com/OpenAEV-Platform/client-python@main|' -i {} \;
       - run:
           working_directory: ~/openaev/http-query
           name: Build Docker image openaev/injector-http-query
@@ -155,6 +209,45 @@ jobs:
       - slack/notify:
           event: fail
           template: basic_fail_1
+  # build_rolling_1:
+  #   working_directory: ~/openaev
+  #   docker:
+  #     - image: cimg/base:stable-20.04
+  #   steps:
+  #     - checkout
+  #     - setup_remote_docker
+  #     - run: sudo apt-get update -qq && sudo apt install curl gettext-base
+  #     - run:
+  #        working_directory: ~/openaev
+  #        name: Replace pyoaev requirement of stable version with latest main branch code
+  #        command: find . -name requirements.txt -exec sed 's|^pyoaev==.*$|pyoaev @ git+https://github.com/OpenAEV-Platform/client-python@main|' -i {} \;
+  #     - run:
+  #         working_directory: ~/openaev/http-query
+  #         name: Build Docker image openaev/injector-http-query
+  #         command: docker build --progress=plain -t openaev/injector-http-query:rolling .
+  #     - run:
+  #         working_directory: ~/openaev/nmap
+  #         name: Build Docker image openaev/injector-nmap
+  #         command: docker build --progress=plain -t openaev/injector-nmap:rolling .
+  #     - run:
+  #         working_directory: ~/openaev/nuclei
+  #         name: Build Docker image openaev/injector-nuclei
+  #         command: docker build --progress=plain -t openaev/injector-nuclei:rolling .
+  #     - run:
+  #         working_directory: ~/openaev/aws
+  #         name: Build Docker image openaev/injector-aws
+  #         command: docker build --progress=plain -t openaev/injector-aws:rolling .
+  #     - run:
+  #         name: Publish Docker Image to Docker Hub
+  #         command: |
+  #           echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
+  #           docker push openaev/injector-http-query:rolling
+  #           docker push openaev/injector-nmap:rolling
+  #           docker push openaev/injector-nuclei:rolling
+  #           docker push openaev/injector-aws:rolling
+  #     - slack/notify:
+  #         event: fail
+  #         template: basic_fail_1
   build_prerelease_1:
     working_directory: ~/openaev
     docker:
@@ -171,30 +264,71 @@ jobs:
       - run:
           working_directory: ~/openaev/http-query
           name: Build Docker image openaev/injector-http-query
-          command: docker build --progress=plain -t openaev/injector-http-query:prerelease -t openbas/injector-http-query:prerelease .
+          command: docker build --progress=plain -t openbas/injector-http-query:prerelease .
       - run:
           working_directory: ~/openaev/nmap
           name: Build Docker image openaev/injector-nmap
-          command: docker build --progress=plain -t openaev/injector-nmap:prerelease -t openbas/injector-nmap:prerelease .
+          command: docker build --progress=plain -t openbas/injector-nmap:prerelease .
       - run:
           working_directory: ~/openaev/nuclei
           name: Build Docker image openaev/injector-nuclei
-          command: docker build --progress=plain -t openaev/injector-nuclei:prerelease -t openbas/injector-nuclei:prerelease .
+          command: docker build --progress=plain -t openbas/injector-nuclei:prerelease .
       - run:
           working_directory: ~/openaev/aws
           name: Build Docker image openaev/injector-aws
-          command: docker build --progress=plain -t openaev/injector-aws:prerelease -t openbas/injector-aws:prerelease .
+          command: docker build --progress=plain -t openbas/injector-aws:prerelease .
       - run:
           name: Publish Docker Image to Docker Hub
           command: |
             echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
-            docker push openaev/injector-http-query:prerelease && docker push openbas/injector-http-query:prerelease
-            docker push openaev/injector-nmap:prerelease && docker push openbas/injector-nmap:prerelease
-            docker push openaev/injector-nuclei:prerelease && docker push openbas/injector-nuclei:prerelease
-            docker push openaev/injector-aws:prerelease && docker push openbas/injector-aws:prerelease
+            docker push docker push openbas/injector-http-query:prerelease
+            docker push docker push openbas/injector-nmap:prerelease
+            docker push docker push openbas/injector-nuclei:prerelease
+            docker push docker push openbas/injector-aws:prerelease
       - slack/notify:
           event: fail
           template: basic_fail_1
+
+  # build_prerelease_1:
+  #   working_directory: ~/openaev
+  #   docker:
+  #     - image: cimg/base:stable-20.04
+  #   steps:
+  #     - checkout
+  #     - setup_remote_docker
+  #     - run: sudo apt-get update -qq && sudo apt install curl gettext-base
+  #     - run:
+  #         working_directory: ~/openaev
+  #         name: Replace pyoaev requirement of stable version with latest release branch code
+  #         # We safely expand the CIRCLE_BRANCH variable because the CircleCI filters already enforce a strict release/x.x.x pattern using regex
+  #         command: find . -name requirements.txt -exec sed "s|^pyoaev==.*$|pyoaev @ git+https://github.com/OpenAEV-Platform/client-python@${CIRCLE_BRANCH}|" -i {} \;
+  #     - run:
+  #         working_directory: ~/openaev/http-query
+  #         name: Build Docker image openaev/injector-http-query
+  #         command: docker build --progress=plain -t openaev/injector-http-query:prerelease -t openbas/injector-http-query:prerelease .
+  #     - run:
+  #         working_directory: ~/openaev/nmap
+  #         name: Build Docker image openaev/injector-nmap
+  #         command: docker build --progress=plain -t openaev/injector-nmap:prerelease -t openbas/injector-nmap:prerelease .
+  #     - run:
+  #         working_directory: ~/openaev/nuclei
+  #         name: Build Docker image openaev/injector-nuclei
+  #         command: docker build --progress=plain -t openaev/injector-nuclei:prerelease -t openbas/injector-nuclei:prerelease .
+  #     - run:
+  #         working_directory: ~/openaev/aws
+  #         name: Build Docker image openaev/injector-aws
+  #         command: docker build --progress=plain -t openaev/injector-aws:prerelease -t openbas/injector-aws:prerelease .
+  #     - run:
+  #         name: Publish Docker Image to Docker Hub
+  #         command: |
+  #           echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
+  #           docker push openaev/injector-http-query:prerelease
+  #           docker push openaev/injector-nmap:prerelease
+  #           docker push openaev/injector-nuclei:prerelease
+  #           docker push openaev/injector-aws:prerelease
+  #     - slack/notify:
+  #         event: fail
+  #         template: basic_fail_1
   deploy_testing:
     docker:
       - image: cimg/base:stable
